// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCymB3QkPVOFCpd6hE4LL0EevBy3FSQ8QI',
    appId: '1:517637478860:android:b340c01a7a6d30a26d2569',
    messagingSenderId: '517637478860',
    projectId: 'library-management-d62e6',
    databaseURL: 'https://library-management-d62e6-default-rtdb.firebaseio.com',
    storageBucket: 'library-management-d62e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGMjKSa1Ujj07_4dAMvIN0a5xxZvA9ooQ',
    appId: '1:517637478860:ios:c57383918244c5566d2569',
    messagingSenderId: '517637478860',
    projectId: 'library-management-d62e6',
    databaseURL: 'https://library-management-d62e6-default-rtdb.firebaseio.com',
    storageBucket: 'library-management-d62e6.firebasestorage.app',
    iosBundleId: 'com.example.libraryBook',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACVBNqQCO6BTxDQ-9Q2bGDkoRWuMkm5Fs',
    appId: '1:517637478860:web:b69d81bc3d79822a6d2569',
    messagingSenderId: '517637478860',
    projectId: 'library-management-d62e6',
    authDomain: 'library-management-d62e6.firebaseapp.com',
    databaseURL: 'https://library-management-d62e6-default-rtdb.firebaseio.com',
    storageBucket: 'library-management-d62e6.firebasestorage.app',
    measurementId: 'G-7V6PB4PD25',
  );

}