// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT2ccY32MbBD8ycuU64fpuQEruaHWZl_A',
    appId: '1:254020979059:web:3994369a476e71028bdd06',
    messagingSenderId: '254020979059',
    projectId: 'ctb-attendance-monitorin-4ead4',
    authDomain: 'ctb-attendance-monitorin-4ead4.firebaseapp.com',
    databaseURL: 'https://ctb-attendance-monitorin-4ead4-default-rtdb.firebaseio.com',
    storageBucket: 'ctb-attendance-monitorin-4ead4.firebasestorage.app',
    measurementId: 'G-HDGX3Y6HGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM0F2XXZVJj6FIReNr61QdS9R5NalcjR0',
    appId: '1:254020979059:android:ca3942d922258b618bdd06',
    messagingSenderId: '254020979059',
    projectId: 'ctb-attendance-monitorin-4ead4',
    databaseURL: 'https://ctb-attendance-monitorin-4ead4-default-rtdb.firebaseio.com',
    storageBucket: 'ctb-attendance-monitorin-4ead4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFKvjTZJzKnzOFN7FWxa0fIN4ncBSpJVI',
    appId: '1:254020979059:ios:279af52edde0d22c8bdd06',
    messagingSenderId: '254020979059',
    projectId: 'ctb-attendance-monitorin-4ead4',
    databaseURL: 'https://ctb-attendance-monitorin-4ead4-default-rtdb.firebaseio.com',
    storageBucket: 'ctb-attendance-monitorin-4ead4.firebasestorage.app',
    iosBundleId: 'com.attendancemonitoring.web',
  );
}
